import { Poppins } from "next/font/google";
import "../styles/main.css"
import Footer from "./components/Footer"
import Navbar from "./components/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body
        className={`${poppins.variable} antialiased`}
      >
        <div className="layout">
        <Navbar/>
        {children}
         <Footer/>
         </div>
      </body>
     
    </html>
  )
}
